### ISSUE TITLE
Orbit tasks fail if the caller shell is not compatible with the `run` expected shell

### ISSUE THREAD

**Issue by octplane** [gulien/orbit#27]
We found out that when designing a simple task such as:

```yaml
run
      - |
        cat > foo.yml <<EOF
        app:
          name: {{ $.Orbit.Values.app.name }}
        EOF
```

it would fail for user having a shell not supporting this syntax (in my case, my `fish` shell is not happy about that:

```shell
fish: Expected a string, but instead found a redirection
cat > foo.yml <<EOF
```

**Comment by gulien** [comment]
Hi @octplane!

Indeed, Orbit is checking the SHELL environment variable on POSIX systems. 
I'd suggest to run Orbit like this:

```bash
$ SHELL=/bin/your_shell orbit run your_task
```

It should solve your problem 😃 

If you don't want to specify the SHELL each time you're running Orbit, you could also have the following `orbit.yml` file:

```yaml
tasks:
  
  - use: main_task
     run:
       - SHELL=/bin/your_shell orbit run sub_task

 - use: sub_task
    private: true
    run:
      - |
        cat > foo.yml <<EOF
        app:
          name: {{ $.Orbit.Values.app.name }}
        EOF 
```
