### ISSUE TITLE
Display short field when running tasks

### ISSUE THREAD

**Issue by octplane** [gulien/orbit#29]
This is a feature request. Not sure this is an actual use case.

In my tasks, I run several generated tasks from one single task (such as `apps:upload` that will upload a bunch of apps on a server). 

The fact that Orbit does not show any information about the tasks it runs is a bit confusing. I had to recode some artificial debug info to make that more easy:

```yaml
{{- $title := printf "Render and deploy app for %s to %s on %s" $.Orbit.Values.app.name $deploy.k8s_cluster $deploy.aws_account}}
  - use: {{ $stage }}
    short: {{ $title}}
    run:
      - echo "{{ $title }}"
```

The alternative is to run `Orbit -d` but this is very verbose!

I wanted to know if it could be possible:
- either have a `-i` (like `info`) flag that would display this information
- or inject an env variable so that the `run` code can access this information
- or always print this information

Let me know what you think of this...
